### ISSUE TITLE
knex 0.14.0 compatibility problem

### ISSUE THREAD

**Issue by codemariner** [alekbarszczewski/knex-hooks#3]
After upgrading our knex to 0.14.0 from 0.13.x, the following error occurred:

```
Error: Cannot find module 'knex/lib/query/builder'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/knex-hooks/src/helpers.js:2:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/knex-hooks/src/knex-hooks.js:8:17)
```

Looks like that no longer exists in knex 0.14.

**Comment by alekbarszczewski** [comment]
@codemariner Thanks for info - I will look into this. Unfortunately knex-hooks relies on internal knex code that may change. I will try to make strict requirements of knex version through peer dependencies and add tests for specific knex versions. However I won't be able to work on it this week - I will take care of at Monday.

**Comment by jaydlawrence** [comment]
This problem exists now since knex moved to 0.95.0.

https://github.com/knex/knex/compare/0.21.17...0.95.0#diff-064c6305016fff5f7df80ad10883851565d770f919dcbd05c6b40f6d9828e8ea

They renamed the `builder` file to `querybuilder` as of 0.95.

I am using the latest knex. I installed `knex-hooks` and manually updated it in my nodemodules to point at `knex/lib/query/querybuilder` and it seems to work. 

It looks like the knex change was done in March 2021, so it is still pretty recent.
I would offer to make a PR, but I don't know how you want to manager the compatibility with older version etc.
